-- 1. Create Parent Table: Staff
CREATE TABLE Staff (
    StaffID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    FirstName NVARCHAR2(50) NOT NULL,
    LastName NVARCHAR2(50) NOT NULL,
    Role VARCHAR2(20) NOT NULL, 
    Username VARCHAR2(50) UNIQUE NOT NULL,
    PasswordHash VARCHAR2(255) NOT NULL
);

-- 2. Create Parent Table: Customer
CREATE TABLE Customer (
    CustomerID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    FirstName NVARCHAR2(50) NOT NULL,
    LastName NVARCHAR2(50) NOT NULL,
    PhoneNumber VARCHAR2(15) NOT NULL,
    Email VARCHAR2(100), 
    Gender NVARCHAR2(10)
);

-- 3. Create Parent Table: Service
CREATE TABLE Service (
    ServiceID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Name NVARCHAR2(100) NOT NULL,
    Price NUMBER(10, 2) NOT NULL,
    DurationMinutes NUMBER NOT NULL 
);

-- 4. Create Child Table: Appointment
CREATE TABLE Appointment (
    AppointmentID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CustomerID NUMBER NOT NULL,
    StaffID NUMBER NOT NULL, 
    AppointmentDateTime TIMESTAMP NOT NULL,
    Status VARCHAR2(20) DEFAULT 'Confirmed',
    
    CONSTRAINT fk_appt_customer FOREIGN KEY (CustomerID) REFERENCES Customer(CustomerID),
    CONSTRAINT fk_appt_staff FOREIGN KEY (StaffID) REFERENCES Staff(StaffID)
);

-- 5. Create Junction Table: Appointment_Detail
CREATE TABLE Appointment_Detail (
    AppointmentID NUMBER NOT NULL,
    ServiceID NUMBER NOT NULL,
    
    PRIMARY KEY (AppointmentID, ServiceID),
    CONSTRAINT fk_detail_appt FOREIGN KEY (AppointmentID) REFERENCES Appointment(AppointmentID),
    CONSTRAINT fk_detail_service FOREIGN KEY (ServiceID) REFERENCES Service(ServiceID)
);
