-- ==========================================
-- 1. INVENTORY CATALOG & INTERNAL CONSUMPTION
-- ==========================================

CREATE TABLE Product (
    ProductID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Name NVARCHAR2(100) NOT NULL,
    ProductType VARCHAR2(20) DEFAULT 'Both' NOT NULL, 
    Category NVARCHAR2(50), -- NEW: Added for reporting and UI grouping (e.g., 'Wax', 'Hair Dye')
    Price NUMBER(10, 2) NOT NULL, 
    BaseUOM VARCHAR2(20) NOT NULL, 
    PurchasingUOM VARCHAR2(20) NOT NULL, 
    ConversionFactor NUMBER(10, 2), 
    
    CONSTRAINT chk_product_type CHECK (ProductType IN ('Retail', 'Professional', 'Both'))
);

CREATE TABLE Service_Recipe (
    ServiceID NUMBER NOT NULL, 
    ProductID NUMBER NOT NULL,
    QuantityConsumed NUMBER(10, 2) NOT NULL, 
    
    PRIMARY KEY (ServiceID, ProductID),
    CONSTRAINT fk_recipe_service FOREIGN KEY (ServiceID) REFERENCES Service(ServiceID),
    CONSTRAINT fk_recipe_product FOREIGN KEY (ProductID) REFERENCES Product(ProductID)
);

CREATE TABLE Inventory_Ledger (
    TransactionID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ProductID NUMBER NOT NULL,
    ChangeAmount NUMBER(10, 2) NOT NULL, 
    TransactionType VARCHAR2(50) NOT NULL, 
    ReferenceID NUMBER, 
    TransactionDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT fk_ledger_product FOREIGN KEY (ProductID) REFERENCES Product(ProductID),
    CONSTRAINT chk_trans_type CHECK (TransactionType IN ('Restock', 'ServiceUse', 'RetailSale', 'Adjustment', 'Return'))
);

-- ==========================================
-- 2. FINANCIAL DOMAIN (Invoicing)
-- ==========================================

CREATE TABLE Bill (
    BillID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    AppointmentID NUMBER, 
    CustomerID NUMBER NOT NULL, 
    BillDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    TotalAmount NUMBER(10, 2) NOT NULL,
    PaymentStatus VARCHAR2(20) DEFAULT 'Pending',
    
    CONSTRAINT fk_bill_appointment FOREIGN KEY (AppointmentID) REFERENCES Appointment(AppointmentID),
    CONSTRAINT fk_bill_customer FOREIGN KEY (CustomerID) REFERENCES Customer(CustomerID),
    CONSTRAINT chk_payment_status CHECK (PaymentStatus IN ('Pending', 'Paid', 'Refunded', 'Failed'))
);

CREATE TABLE Bill_Detail (
    BillDetailID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    BillID NUMBER NOT NULL,
    ServiceID NUMBER, 
    ProductID NUMBER, 
    Quantity NUMBER NOT NULL,
    UnitPrice NUMBER(10, 2) NOT NULL, 
    LineTotal NUMBER(10, 2) GENERATED ALWAYS AS (Quantity * UnitPrice) VIRTUAL, 
    
    CONSTRAINT fk_bd_bill FOREIGN KEY (BillID) REFERENCES Bill(BillID),
    CONSTRAINT fk_bd_service FOREIGN KEY (ServiceID) REFERENCES Service(ServiceID),
    CONSTRAINT fk_bd_product FOREIGN KEY (ProductID) REFERENCES Product(ProductID),
    
    CONSTRAINT chk_mutually_exclusive_item CHECK (
        (ServiceID IS NOT NULL AND ProductID IS NULL) 
        OR 
        (ServiceID IS NULL AND ProductID IS NOT NULL)
    )
);
